# Generated by Django 3.1.2 on 2021-11-29 04:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_linked', models.ImageField(blank=True, null=True, upload_to='article/images/')),
                ('video_linked', models.FileField(blank=True, null=True, upload_to='article/videos/')),
                ('doc_linked', models.FileField(blank=True, null=True, upload_to='article/docs')),
                ('media_type', models.CharField(max_length=6, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 4, 48, 24, 593748))),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL)),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
    ]
